### PR TITLE
Hardware support added. Multiple card selection added. Multiboot support.

### PR DESCRIPTION
**Pull request by Gannio**
This pull request adds real hardware support, as well as sets the makefile to compile a multiboot rom, to make it more accessible for those that have access to a homebrewed Wii (via [gba-link-cable-rom-sender](https://github.com/FIX94/gba-link-cable-rom-sender)). It also has been redesigned to allow the user to select from multiple cards at a time, as opposed to one per type of card.

It should in theory be able to support most, if not every officially released level card and powerup card within the 256KB limit of a multiboot. However, it can't support every demo card alongside this, as that exceeds the limit by around 60KB. Finding a way to compress the data in the multiboot (Especially for powerup cards, which have a lot of filler data to pad out the dotcode) would help circumvent this.

The changelogs of the first commit should provide more details onto exact code changes.

[Hardware demonstration video.](https://www.youtube.com/watch?v=7NANEv4VCXU)

### CODE REVIEW

**Comment by LuigiBlood** [comment]
This is actually nice.

It doesn't compile if I don't remove these three lines. I assume these are accidental and have no actual use.
https://github.com/Gannio/sma4comm/blob/master/source/main.c#L13-L15

I may recommend casting to `(u16*)` just so we get less warnings about the code even if it definitely works anyway, it's just nicer.
https://github.com/Gannio/sma4comm/blob/master/source/main.c#L304
https://github.com/Gannio/sma4comm/blob/master/source/main.c#L309

I may do further changes just for European and Japanese support because Nintendo really made this annoying.
I don't have a good real hardware setup as of right now so I can't test this as I want easily (though thanks for mentioning [gba-link-cable-rom-sender](https://github.com/FIX94/gba-link-cable-rom-sender) I didn't know about that).

**Comment by Gannio** [comment]
Yeah those were left in by accident. Updated version should have those removed, as well as the casting to (u16*).

If you want me to test something out on hardware let me know, though I only have access to the U.S. version as a heads up.

**Comment by LuigiBlood** [comment]
I have access to a flashcart and should have means to test just that I need to replug a lot of stuff and get a good environment and everything.
For the sake of clean pull requests though, I'll treat regions as outside the scope of this PR.

**Comment by LuigiBlood** [comment]
Okay I tested it it's all great :)

**Pull request merged**
